#!/usr/bin/env bash
# Daha basit çözüm (for döngüsü olmadan)

awk '
    {
        count[$1 " " $9]++
    }
    END {
        for (combo in count) {
            print count[combo], combo | "sort -k1,1nr -k2,2"
        }
    }
' apache-access.log 2>/dev/null
