#!/usr/bin/env bash
# This script checks information about the school file

file="school"

# Check if file exists
if [ -e "$file" ]; then
    echo "$file file exists"
    
    # Check if file is empty
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
    
    # Check if it's a regular file
    if [ -f "$file" ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
